print("hi friends")
print("hi","siva")
print("hi"+"siva"+"good"+"morning")
print("hi","friends","lets","go",sep="**")
print("I","am","siva",sep="\n")
print("hi","friends","lets","go",sep="\t")
print("hello",end=" ")
print("siva")
print("&")
print("kumar")